### ISSUE TITLE
Offset being ignored when calling ChargeBee::Customer.list({:limit => limit, :offset => offset})

### ISSUE THREAD

**Issue by sebastiansibelle** [chargebee/chargebee-ruby#2]
Hi there,

I've found a bug in Chargebee Gem (1.4.6), where the offset parameter is being ignored when called in the ChargeBee::Customer.list({:limit => limit, :offset => offset}) function. Where limit is an int and offset is returned from a previous call to ChargeBee::Customer.list(). 

I should be able to pass in an offset returned from the last call, and get the next set of results as per the documentation here: https://apidocs.chargebee.com/docs/api/customers#list_customers
However, I always get the same results regardless of what offset value is supplied.

I've prepared a gist to help illustrate the point here: https://gist.github.com/sebastiansibelle/4a374f1ffa4ebfc40633

I need to use this function very soon, so the quicker you could turn around a fix the better!

Thanks,

Sebastian

**Comment by vaibhav1510** [comment]
Hey Sebastian,

We have released the updated version hence closing this issue.

**Comment by Shahtaj-Khalid** [comment]
@saravana-cb @sebastiansibelle @vaibhav1510  hi, 
I came across an issue while accessing offset to and i'm unable to figure out how the request will look like for accessing next offset. i'm trying something like this (https://sh1testcompany-test.chargebee.com/api/v2/events/offset?next_offset[is]=1550749829000) but it's not working kindly help me out, it will be really appreciated. Thanks.

**Comment by cb-goutham** [comment]
@Shahtaj-Khalid Hi , 
The request will look like this : [https://sh1testcompany-test.chargebee.com/api/v2/events?limit=2&offset=["1551079043000","348000000200"]](url) . You can get the offset value from your previous list request ( list.next_offset.to_s) 

**Example :** 

```
list = ChargeBee::Event.list({
  :limit => 2
  })
list1 = ChargeBee::Event.list({
	:limit => 2,
	:offset => list.next_offset.to_s
})
list1.each do |entry|
  event = entry.event
  puts event.id
 end
```
