### ISSUE TITLE
json_pure version

### ISSUE THREAD

**Issue by jjb** [chargebee/chargebee-ruby#28]
What is the reason for holding back the json_pure version?

If it's to support older versions of ruby, someone in that situation can deal with that by holding the version back themselves in their own Gemfile.

**Comment by jjb** [comment]
Hi @SangeethaBaskaran - why did this get closed?

**Comment by glnarayanan** [comment]
Hi @jjb this is now fixed. We have updated the json_pure version on the recent release.

**Comment by jjb** [comment]
Thanks!
