### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by raldred** [chargebee/chargebee-ruby#37]
Hey, Just a quick one. 
It might be helpful to give a quick summary on the first line of the commit messages to this repo.
The detail when you dig into them is great but because the first line is just stars it makes a flick through the git commit log pretty difficult to establish what's happening.

![image](https://user-images.githubusercontent.com/37096/52702932-2631fc80-2f75-11e9-92a8-4ed89b92fcf5.png)

**Comment by cb-khushbubibay** [comment]
@raldred  Thanks for your suggestion. 
We have started commenting initial statement in our commit message form release version 2.13.1 and will follow the same.
Hence closing this issue.
