### ISSUE TITLE
.DS_Store File in Repo

### ISSUE THREAD

**Issue by sshaw** [chargebee/chargebee-ruby#39]
https://github.com/chargebee/chargebee-ruby/blob/master/lib/.DS_Store

**Comment by evolve2k** [comment]
Pretty minor. I suggest open a PR so this can be resolved with a button click.

**Comment by norioumata** [comment]
Added PR
https://github.com/chargebee/chargebee-ruby/pull/57

**Comment by cb-prajaktachavan** [comment]
Closing this issue as PR [#57](https://github.com/chargebee/chargebee-ruby/pull/57) is already fixed.
