### ISSUE TITLE
puts statements in method_missing

### ISSUE THREAD

**Issue by davidw** [chargebee/chargebee-ruby#41]
I'm trying to simply do a `puts chargebee_result`, but this gets printed out:

https://github.com/chargebee/chargebee-ruby/blob/master/lib/chargebee/models/model.rb#L49

It might be better to have that output to `STDERR`, so as to not interfere with scripts trying to simply print out the result object.

**Comment by cb-khushbubibay** [comment]
This issue has been addressed in v2.13.1. Hence closing it.
