### ISSUE TITLE
Consider adopting semantic versioning

### ISSUE THREAD

**Issue by dogweather** [chargebee/chargebee-ruby#44]
It'd help application developers write more reliable apps. E.g., how Rails uses version numbers. Thanks for your consideration!

https://semver.org

**Comment by cb-khushbubibay** [comment]
Hi @dogweather 
Thank you for your suggestion! We greatly appreciate your input. We're pleased to inform you that we have already implemented a versioning strategy similar to how Rails uses version numbers. This approach will indeed help application developers write more reliable apps.

**Comment by dogweather** [comment]
Excellent.
