### ISSUE TITLE
Regression bug: #to_s incorrectly private

### ISSUE THREAD

**Issue by dogweather** [chargebee/chargebee-ruby#45]
This [commit](https://github.com/chargebee/chargebee-ruby/commit/08127609d5f3c8611a3ff0cc8c4fa222fc3eef9a#diff-9422727fbe8b4678385e18c368f7fdb9) made `#to_s` public, which is actually [very important](https://github.com/chargebee/chargebee-ruby/pull/36). 

But then [this later commit](https://github.com/chargebee/chargebee-ruby/commit/c24a111f2c19c8a86f0f9c725867d3b6916e81af#diff-9422727fbe8b4678385e18c368f7fdb9R209) made it private again. (The `private` statement appears twice in the file now, and looks like a copy & paste error.)

This is blocking me from upgrading. (I'm currently using my own private fork where I've fixed this.)

**Comment by cb-gaurav** [comment]
Hi @dogweather. Thanks for bringing this to our notice. We will fix it asap and update you.

**Comment by dogweather** [comment]
Thank you!

**Comment by cb-gaurav** [comment]
Hi @dogweather . The issue has been fixed. Closing this
