### ISSUE TITLE
Make HTTP timeout configurable

### ISSUE THREAD

**Issue by TimKaechele** [chargebee/chargebee-ruby#52]
## Description

After the recent availability problems of the ChargeBee service, I had problems in my own service that relies on chargebee due to the long timeouts set in the ChargeBee ruby client. Therefore I would like to propose that the SDK allows a user to specify to set their own HTTP timeout limits as a configuration parameter.

**Comment by cb-prajaktachavan** [comment]
Already provision made to configure HTTP timeout. This has been merged in v2.11.0. You can set own http connect and read timeouts using ChargeBee.update_connect_timeout_secs() and ChargeBee.update_read_timeout_secs().
