### ISSUE TITLE
Contract Term Model should be included

### ISSUE THREAD

**Issue by sunenilausen** [chargebee/chargebee-ruby#56]
The model class https://github.com/chargebee/chargebee-ruby/blob/master/lib/chargebee/models/contract_term.rb

Is not included in
https://github.com/chargebee/chargebee-ruby/blob/master/lib/chargebee.rb

To reproduce try https://apidocs.chargebee.com/docs/api/subscriptions?prod_cat_ver=1&lang=ruby#list_contract_terms_for_a_subscription

```ruby
require 'chargebee'
ChargeBee.configure(:site => "{site}",
  :api_key => "{site_api_key}")
list = ChargeBee::Subscription.contract_terms_for_subscription("__test__8asukSOXdty0Mv")
list.each do |entry|
  contract_term = entry.contract_term
end
```

=> (uninitialized constant ChargeBee::Result::ContractTerm)
Did you mean?  ChargeBee::Contact

**Comment by cb-rakesh** [comment]
> The model class https://github.com/chargebee/chargebee-ruby/blob/master/lib/chargebee/models/contract_term.rb
> 
> Is not included in
> https://github.com/chargebee/chargebee-ruby/blob/master/lib/chargebee.rb
> 
> To reproduce try https://apidocs.chargebee.com/docs/api/subscriptions?prod_cat_ver=1&lang=ruby#list_contract_terms_for_a_subscription
> 
> ```ruby
> require 'chargebee'
> ChargeBee.configure(:site => "{site}",
>   :api_key => "{site_api_key}")
> list = ChargeBee::Subscription.contract_terms_for_subscription("__test__8asukSOXdty0Mv")
> list.each do |entry|
>   contract_term = entry.contract_term
> end
> ```
> 
> => (uninitialized constant ChargeBee::Result::ContractTerm)
> Did you mean? ChargeBee::Contact

Could you update to the latest version to use the feature?
