### ISSUE TITLE
Changelog address missing from gemspec file

### ISSUE THREAD

**Issue by girardof** [chargebee/chargebee-ruby#69]
The `chargebee.gemspec` doesn't contain a link to the changelog of the project, this prevent Dependabot to automatically fetch the changes made in new versions.

Here's a screenshot for the latest version of Chargebee-ruby:

![Screenshot 2023-06-01 at 08 44 29](https://github.com/chargebee/chargebee-ruby/assets/36230226/174c60ed-3efe-49a7-ba8b-77c34999d5f1)

A simple way to fix is to add the following key in `chargebee.gemspec`: 

```ruby
s.metadata = {
  "changelog_uri" => "https://github.com/chargebee/chargebee-ruby/blob/master/CHANGELOG.md",
}
```

You can find the documentation about the metadata key [here](https://guides.rubygems.org/specification-reference/#metadata).

**Comment by cb-khushbubibay** [comment]
Hi @girardof 
The functionality mentioned has been implemented in version [v2.28.0](https://rubygems.org/gems/chargebee) of the library. To take advantage of this feature, kindly update the library to the mentioned version.
