### ISSUE TITLE
Bad uri error fetching Customer Data

### ISSUE THREAD

**Issue by ActualAl** [chargebee/chargebee-ruby#70]
HTML encode requests for customer and subscription data.

In Chargebee we setup a customer with an ID like the following `Customer [Dotcom]`. The Chargebee UI allows this as a valid name. When calling for the customer data via the gem `ChargeBee::Customer.retrieve(team.chargebee_customer_id)` the gem throws a bad uri error

bad URI(is not URI?): "https://captionhub.chargebee.com/api/v2/customers/Customer%20[Dotcom]"

It looks like the gem could benefit from some further encoding

**Comment by ActualAl** [comment]
I looks like it's square brackets in the customer name that is the issue

**Comment by cb-khushbubibay** [comment]
Hi @ActualAl 
Thanks for raising the concern.
This issue has been fixed in out latest chargebee-ruby v2.29.0. Request you to please update the package.
