### ISSUE TITLE
custom fields with spaces causing the API to fail

### ISSUE THREAD

**Issue by macharmi** [chargebee/chargebee-ruby#72]
The recent changes in the UI allowed users to insert custom attributes with spaces. 

![image](https://github.com/chargebee/chargebee-ruby/assets/9129169/cf675cef-8547-44d8-913c-37773683ebe5)

This is causing a bug in the API.

```
::ChargeBee::Customer.retrieve('test-custome-id', environment).customer
NameError: `@cf_my My customer field' is not allowed as an instance variable name
from /usr/local/bundle/gems/chargebee-2.31.1/lib/chargebee/models/model.rb:39:in `instance_variable_set'
```

**Comment by fmarkwong** [comment]
@chargebee, any updates on this issue?  You guys have a field on Subscription that has a space "cf_Subscription Type" and this Ruby library chokes on it.  It's quite a blocker.  Thanks.

**Comment by fmarkwong** [comment]
Looks like this issue was fixed as of v2.35.0.  Issue can probably be closed.  Thanks for fixing it!

**Comment by cb-sriramthiagarajan** [comment]
Hi @macharmi, I'm sorry for the delayed response. As @fmarkwong mentioned, this was fixed so I'll go ahead and close this issue.

Thanks for the note @fmarkwong :)

**Comment by macharmi** [comment]
Thank you @cb-sriramthiagarajan ! We are already using the new version.
