### ISSUE TITLE
Missing Chargebee::Entitlements include

### ISSUE THREAD

**Issue by jfloff** [chargebee/chargebee-ruby#75]
Recently, you guys added the Chargebee::Entitlements model, but I think you forgot to include it in `lib/chargebee.rb` so it's callable.

**Comment by cb-alish** [comment]
Hi @jfloff I am sorry for the delayed response. Thank you for raising this issue. We have fixed this in our latest release. 

Can you please let us know if you're still facing this issue? This is working fine for us in the latest version of the SDK.

**Comment by cb-sriramthiagarajan** [comment]
Hi @jfloff, I'm closing this issue as it's been fixed in the latest version. Please feel free to reopen this or create a new issue if you find any other problems.
