### ISSUE TITLE
Typo and wrong version in dev dependencies 

### ISSUE THREAD

**Issue by kubenstein** [chargebee/chargebee-ruby#8]
hi, while debugging other stuff i noticed that you have typo in dependencies. also i had to upgrade rspec version to get specs working
it should be:
```
s.add_development_dependency('rspec', '~> 3.0.0')
instead:
s.add_development_dependency('rpsec', '~> 2.9.0')
                          typo ^          ^ version

```

**Comment by vaibhav1510** [comment]
Thank you Jakub for notifying this. We have fixed this in latest release.
