### ISSUE TITLE
Authentication header missing

### ISSUE THREAD

**Issue by MaTsou** [chargebee/chargebee-ruby#84]

**Comment by cb-sriramthiagarajan** [comment]
Hi @MaTsou, can you elaborate the issue please?

**Comment by MaTsou** [comment]
Sorry. A mistake.
I am trying to delete this issue but can't find where it can be done..

**Comment by cb-sriramthiagarajan** [comment]
No worries, I'll close this. Please feel free to open a new one if you run into any issues.
